CREATE DATABASE COMPANY;

SELECT *
FROM DEPT;

SELECT DISTINCT JOB 
FROM EMP;

SELECT *
FROM EMP
WHERE SAL >2200; 

SELECT ENAME, DEPTNO
FROM EMP
WHERE HIREDATE < '1981-05-12';

SELECT CONCAT(ENAME, ' IS A ' ,JOB)
AS `Employee Details`
FROM EMP;

SELECT E.ENAME ,E.JOB, D.DNAME
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO;

SELECT A.ENAME ,A.JOB, D.DNAME,D.LOCATION
FROM EMP A,DEPT D
WHERE A.DEPTNO=D.DEPTNO;
